server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ch-shubham/POC-Learning.git
          default-label: master
          clone-on-start: true
          username: test-user
          password: ENC(testing)
          search-paths:
            - Spring-Cloud-Config/config-store/dev
            - Spring-Cloud-Config/config-store/uat
            - Spring-Cloud-Config/config-store/prod
    compatibility-verifier:
      enabled: false

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    salt-generator-classname: org.jasypt.salt.RandomSaltGenerator
    password: testing
